spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**


server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ${jwt_secret}