spring.application.name=user-service

server.port=8081

spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.url=jdbc:postgresql://localhost:5432/ssuser

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

#JWT#
jwt.secret=${jwt_secret}
jwt.expiration=900000