spring.application.name=order-service


server.port=8083

spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.url=jdbc:postgresql://localhost:5432/ss_order

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

#Resilience 4j

#sliding-window size is how many request resilience 4j check ( in this case last 10 request)
resilience4j.circuitbreaker.instances.productService.sliding-window-size=10


resilience4j.circuitbreaker.instances.productService.failure-rate-threshold=50
#failure-rate-threshold: how many request should fail to open the circuit

resilience4j.circuitbreaker.instances.productService.wait-duration-in-open-state=10s
# this is the time until which the circuit is open for 10s then move to half open

resilience4j.circuitbreaker.instances.productService.permitted-number-of-calls-in-half-open-state=3
# number of request allowed in half open state

resilience4j.circuitbreaker.instances.productService.automatic-transition-from-open-to-half-open-enabled=true
# automatically move to half open after the wait time

resilience4j.circuitbreaker.instances.productService.register-health-indicator=true

####### Retry ########
resilience4j.retry.instances.productService.max-attempts=3
resilience4j.retry.instances.productService.wait-duration=500ms

######## Rate limiter #####
resilience4j.ratelimiter.instances.productService.limit-for-period=2
resilience4j.ratelimiter.instances.productService.limit-refresh-period=10ms
resilience4j.ratelimiter.instances.productService.timeout-duration=0

# try circuit state in /actuator/health

# Actuator

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

#### KAFKA #####
spring.kafka.bootstrap.servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false


